vim.opt.tabstop = 4
vim.opt.softtabstop = 4
vim.opt.expandtab = true
vim.opt.smarttab = true
vim.opt.swapfile = false
vim.opt.backup = false
vim.opt.signcolumn = 'yes'
--vim.g.material_style = "palenight"
--vim.cmd 'colorscheme material'
vim.cmd 'colorscheme gruvbox'
vim.g.loaded = 1
vim.g.loaded_netrwPlugin = 1
